### PR TITLE
Added option to ingnore the first word of a filename when syncing

### PR DESCRIPTION
**Pull request by ArchieAtkinson**
As suggested in issue #7, this feature provides the option to ignore everything before the first space in the filename when syncing between filename and title.

### CODE REVIEW

**Comment by dvcrn** [comment]
Could you give an example for when this feature would be useful? I'm trying to think of some usecases when this is wanted

**Comment by ArchieAtkinson** [comment]
I can see if being used like in #7 with the zettal timestamps.

**Comment by dvcrn** [comment]
Okay yeah that makes sense. Wonder if a regex pattern would be better to make it more generic, what do you think?

**Comment by ArchieAtkinson** [comment]
That sounds like a more elegant solution. However, regex isn't very user friendly and could potentially be quite destructive if you incorrectly so I can imagine you would want to have a live regex preview where you provide sample text and it tells you what it would sync. You could also provide some basic examples that people can just paste in inside the README.md.

**Comment by dvcrn** [comment]
How about a simpler matching syntax? 

- MyNotes/Hello.md
- Foo.md
- Bar.md
- FooBar.md
- 123452 MyNote.md

Could be:
- MyNotes/*
- Foo.md
- Foo*
- `{word} `

or something like that 🤔
Regex is probably easier if we can make it so you can immediately see what it matches with live-preview

**Comment by dvcrn** [comment]
For the live-preview, how about we fetch list of documents and display to the user which ones are ignored in realtime?

**Comment by ArchieAtkinson** [comment]
Okay, I have spent the last couple of hours trying to implement this but ran into many problems going from the title to the filename. If you would like to have a go at implementing it let me know, if not I suggest we implement something simpler. 

My suggestion is two options, a text box and a tickbox. The text box is for a separator and the tick box indicates if it should remove the first or last instance. For example:

Separator: " " 
Tickbox: First 
Filename: "1234 Note"
Title: "Note"

Separator: "-" 
Tickbox: Last
Filename: "12/04/21 - Daily Notes"
Title: "12/04/21"

etc.

Thoughts?

**Comment by dvcrn** [comment]
Can you upload your attempts if they are in an ok-ish shape? I'll take a look 👀

**Comment by dvcrn** [comment]
I've added regex ignoring to the plugin in https://github.com/dvcrn/obsidian-filename-heading-sync/pull/12

**Comment by ArchieAtkinson** [comment]
I think we are talking about different things. What you have added I for ignoring files completely, whilst what is requested in #7 is the ability to strip something for the filename and have the reset of it sync up. Does that make sense?

**Comment by dvcrn** [comment]
ah whoops - yeah you're right. In either way, it's now possible to ignore files 😄

**Comment by dvcrn** [comment]
@ArchieAtkinson do you still want to get this up? Otherwise I'll close this PR for now

**Comment by ArchieAtkinson** [comment]
Yeah I’m happy to close this

**Pull request closed without merging**
